version: '3.8'

services:
  mysql:
    image: mysql:9
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: customersdb
      MYSQL_USER: customers-service-user
      MYSQL_PASSWORD: customers-service-password
    ports:
      - "3306:3306"
    networks:
      - trino-network
    volumes:
      - mysql_data_v2:/var/lib/mysql

  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: reservations-service-user
      POSTGRES_PASSWORD: reservations-service-password
      POSTGRES_DB: reservationsdb
    ports:
      - "5432:5432"
    networks:
      - trino-network
    volumes:
      - postgres_data_v2:/var/lib/postgresql/data

  mongo:
    image: mongo:5.0.14
    container_name: mongo
    environment:
      MONGO_INITDB_DATABASE: retaildb
      MONGO_INITDB_ROOT_USERNAME: retail-service-user
      MONGO_INITDB_ROOT_PASSWORD: retail-service-password
    ports:
      - "27017:27017"
    networks:
      - trino-network
    volumes:
#      - mongo_data_v10:/data/db
      - $PWD/retail-service/src/main/resources/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js

  trino:
    image: trinodb/trino:474
    container_name: trino
    ports:
      - "8090:8080"
    networks:
      - trino-network
    volumes:
      - $PWD/trino/catalogs:/etc/trino/catalog

networks:
  trino-network:
    driver: bridge

volumes:
  postgres_data_v2:
#  mongo_data_v10:
  mysql_data_v2:
