version: '3.8'

services:
  mysql:
    image: mysql:9
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: customersdb
      MYSQL_USER: customers-service-user
      MYSQL_PASSWORD: customers-service-password
    ports:
      - "3306:3306"
    networks:
      - trino-network
    volumes:
      - mysql_data_v2:/var/lib/mysql

  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: reservations-service-user
      POSTGRES_PASSWORD: reservations-service-password
      POSTGRES_DB: reservationsdb
    ports:
      - "5432:5432"
    networks:
      - trino-network
    volumes:
      - postgres_data_v2:/var/lib/postgresql/data

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - trino-network
    volumes:
      - mongo_data_v1:/data/db

  trino:
    image: trinodb/trino:473
    container_name: trino
    ports:
      - "8090:8080"
    networks:
      - trino-network
    volumes:
      - $PWD/trino/catalogs:/etc/trino/catalog

networks:
  trino-network:
    driver: bridge

volumes:
  postgres_data_v2:
  mongo_data_v1:
  mysql_data_v2:
  trino:
